jest.mock('googleapis', () => {
  const mockOAuth2Instance = {
    generateAuthUrl: jest.fn(),
    getToken: jest.fn(),
    setCredentials: jest.fn(),
    getAccessToken: jest.fn(),
  };
  const mockGmailClient = {
    users: { getProfile: jest.fn() },
  };
  const mockOAuth2ApiClient = {
    userinfo: { get: jest.fn() },
  };
  return {
    google: {
      auth: { OAuth2: jest.fn(() => mockOAuth2Instance) },
      gmail: jest.fn(() => mockGmailClient),
      oauth2: jest.fn(() => mockOAuth2ApiClient),
    },
    __mockOAuth2Instance: mockOAuth2Instance,
    __mockGmailClient: mockGmailClient,
    __mockOAuth2ApiClient: mockOAuth2ApiClient,
  };
});

const googleapis = require('googleapis');
const {
  getAuthUrl,
  getSignInAuthUrl,
  exchangeCodeForTokens,
  getAccessToken,
  getUserEmailAddress,
  getGoogleIdentity,
} = require('../../src/lib/googleOAuth');

describe('googleOAuth', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('getAuthUrl returns the URL generated by the OAuth client with the right scopes', () => {
    googleapis.__mockOAuth2Instance.generateAuthUrl.mockReturnValue('https://accounts.google.com/o/oauth2/mock-url');
    const url = getAuthUrl();
    expect(url).toBe('https://accounts.google.com/o/oauth2/mock-url');
    expect(googleapis.__mockOAuth2Instance.generateAuthUrl).toHaveBeenCalledWith(
      expect.objectContaining({
        access_type: 'offline',
        scope: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'],
      })
    );
  });

  test('exchangeCodeForTokens returns the tokens from getToken', async () => {
    googleapis.__mockOAuth2Instance.getToken.mockResolvedValue({ tokens: { access_token: 'abc', refresh_token: 'xyz' } });
    const tokens = await exchangeCodeForTokens('auth-code-123');
    expect(tokens).toEqual({ access_token: 'abc', refresh_token: 'xyz' });
    expect(googleapis.__mockOAuth2Instance.getToken).toHaveBeenCalledWith('auth-code-123');
  });

  test('getAccessToken sets the refresh token as credentials and returns a fresh access token', async () => {
    googleapis.__mockOAuth2Instance.getAccessToken.mockResolvedValue({ token: 'fresh-access-token' });
    const token = await getAccessToken('some-refresh-token');
    expect(token).toBe('fresh-access-token');
    expect(googleapis.__mockOAuth2Instance.setCredentials).toHaveBeenCalledWith({ refresh_token: 'some-refresh-token' });
  });

  test('getUserEmailAddress returns the profile email address', async () => {
    googleapis.__mockGmailClient.users.getProfile.mockResolvedValue({ data: { emailAddress: 'kenny@igtfreight.com' } });
    const email = await getUserEmailAddress('some-access-token');
    expect(email).toBe('kenny@igtfreight.com');
    expect(googleapis.__mockOAuth2Instance.setCredentials).toHaveBeenCalledWith({ access_token: 'some-access-token' });
  });

  test('getSignInAuthUrl requests identity scopes plus the Gmail scopes, offline with forced consent', () => {
    googleapis.__mockOAuth2Instance.generateAuthUrl.mockReturnValue('https://accounts.google.com/o/oauth2/mock-signin-url');
    const url = getSignInAuthUrl();
    expect(url).toBe('https://accounts.google.com/o/oauth2/mock-signin-url');
    expect(googleapis.__mockOAuth2Instance.generateAuthUrl).toHaveBeenCalledWith({
      access_type: 'offline',
      prompt: 'consent',
      scope: [
        'openid',
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
        'https://www.googleapis.com/auth/gmail.readonly',
        'https://www.googleapis.com/auth/gmail.send',
      ],
    });
  });

  test('getGoogleIdentity returns the stable Google id and verified email', async () => {
    googleapis.__mockOAuth2ApiClient.userinfo.get.mockResolvedValue({
      data: { id: 'google-sub-123', email: 'kenny@igtfreight.com', verified_email: true, name: 'Kenny' },
    });
    const identity = await getGoogleIdentity('some-access-token');
    expect(identity).toEqual({ googleId: 'google-sub-123', email: 'kenny@igtfreight.com', emailVerified: true, name: 'Kenny' });
    expect(googleapis.__mockOAuth2Instance.setCredentials).toHaveBeenCalledWith({ access_token: 'some-access-token' });
  });
});
